apiVersion: v1
kind: Service
metadata:
  name: yopass
  namespace: yopass
  labels:
    app: yopass
spec:
  type: ClusterIP 
  selector:
    app: yopass
  ports:
    - protocol: TCP
      port: 8082  
      targetPort: 8082  # Yopass container port
